spring:
    application:
        name: pconnect-gate
    redis:
        host: localhost
        database: 7
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 0
          max-wait: -1
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

server:
    port: 8965

  # path: /pconnect-user/*只能匹配一个级别，path: /pconnect-user/**可以匹配后面任意个/
zuul:
  # 使用application.yml文件配置zuul的routes，那么这里的路由列表按照书写顺序存在优先级，如果使用的是properties文件配置，则失去优先级这个特性，所以，如果要使用优先级，必须使用yaml文件配置
  routes:
    pconnect-user:
      path: /pconnect-user/**
      serviceId: pconnect-user
    pconnect-todo:
      path: /pconnect-todo/**
      serviceId: pconnect-todo
    pconnect-knw:
      path: /pconnect-knw/**
      serviceId: pconnect-knw
    analysis-spc:
      path: /analysis-spc/**
      serviceId: analysis-spc
    legacy:
      path: http://localhost:8041
  sensitive-headers:
  host:
     connect-timeout-millis: 60000
     socket-timeout-millis: 60000
#  ignored-services: '*'
#  prefix: /api
#  stripPrefix: true  //这个stripPrefix的作用，实际测试好像和文档中说的不一样

# 负载均衡
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 3000

#ribbon:
#  eureka:
#    enabled: false
#
#pconnect-user:
#  ribbon:
#    listOfServers: http://localhost:8964,http://localhost:7964


#        prefer-ip-address: true
eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        serviceUrl:
            defaultZone: http://localhost:8961/eureka/
security:
    oauth2:
      client:
        client-id: pconnect-client
        client-secret: pconnect-secret
        scope: read,write
        auto-approve-scopes: '.*'
        grant-type: password
    user:
        name: admin
        password: admin
        role: USER
    basic:
      enabled: false

# 熔断器，后备服务
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true


github:
  client:
    clientId: 5a2351a20bbb4297592f
    clientSecret: 10f9ec57ffb067dd34214656aa3971fb31e7d500
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    authenticationScheme: query
    clientAuthenticationScheme: form
#    pre-established-redirect-uri: http://localhost:8090/login/github
#    registered-redirect-uri: http://localhost:8090/login/github
#    use-current-uri: false
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    com.netflix: debug
